sonar.projectKey=ynov-react-app
sonar.projectName=YNOV React App
sonar.projectVersion=1.0

# مسار الكود المصدري
sonar.sources=frontend/src
sonar.exclusions=**/node_modules/**,**/*.test.js,**/*.spec.js

# اللغة
sonar.language=js
sonar.javascript.file.suffixes=.js,.jsx

# الترميز
sonar.sourceEncoding=UTF-8
